# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ANSR Lab
email: admin@ansr.cs.utah.edu
description: > # this means to ignore newlines until "baseurl:"
  The Advanced Networks Systems Research (ANSR) lab at the <a href="http://www.utah.edu">University of Utah</a>
  is working on technologies, protocols and applications encompassing mobile and pervasive
  systems and wireless networks, network security and reliability, overload and
  congestion control, multicast communication, network architectures, network management,
  network measurements and models.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://ansr.cs.utah.edu" # the base hostname & protocol for your site
url: http://ansr.cs.utah.edu

# Build settings
markdown: kramdown
