title: ANSR Lab
email: admin@ansr.cs.utah.edu
description: >
  The Advanced Networks Systems Research (ANSR) lab at the <a
  href="http://www.utah.edu">University of Utah</a> is working on
  technologies, protocols and applications encompassing mobile and pervasive
  systems and wireless networks, network security and reliability, Internet of
  things, data privacy, crowdsourcing, overload and congestion control,
  network architectures, network management, network measurements and models.

baseurl: ""
url: http://ansr.cs.utah.edu

markdown: kramdown
