title: ANSR Lab
email: admin@ansr.cs.utah.edu
description: >
  The Advanced Networks Systems Research (ANSR) lab at the <a
  href="http://www.utah.edu">University of Utah</a> is working on
  technologies, protocols and applications encompassing mobile and pervasive
  systems and wireless networks, security, privacy, and reliability, Internet
  of Things, crowdsourcing, dynamic spectrum access, network resource
  management, network measurements and models, and social network
  applications.

baseurl: ""
url: http://ansr.cs.utah.edu

markdown: kramdown
